# Base configs
baseurl: "https://yrushil.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Rushil"
subtitle: 
author: "Rushil Yerrabelli"
header:
 title: "Photography"
 subtitle: "by Rushil Yerrabelli"
footer:
 name: "Hey there, my name is Rushil"
 bio: "Here are some of the best photos I have taken... mostly of wildlife in backyard."
 github: 
web_design: "Template Courtesy of Ram Patra Photography"
social_urls:
  facebook: 
  twitter: 
  instagram: 
  dribbble: 
  linkedin: 
  github: 
